config/routes.rb
Proj::Application.routes.draw do

  resources :selllines

  resources :invoices

  resources :orderlines

  resources :orders

  resources :inventories

  get 'invoices\ireport'=> 'invoices#ireport', as: "orderReport"
  get 'invoices\oreport'=> 'orders#oreport', as: "orepo"

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :orderlines
  has_many :orders, :through => :orderlines

  validates :item_name, :presence => true
  validates :sell_price, :presence =>true
  validates :high, :presence => true
  validates :low, :presence =>true
  validates :item_name, :uniqueness => {:message => " being used"}
  validates_numericality_of :high,:only_integer => true
  validates_numericality_of :low,:only_integer => true
  validates_numericality_of :sell_price,:only_float => true
  validates :high, :numericality => { :greater_than_or_equal_to => 10, :less_than_or_equal_to => 40 }
  validates :low, :numericality => { :greater_than_or_equal_to => 3, :less_than_or_equal_to => 10 }
  validates :item_name, length: { maximum: 30}



end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render action: 'show', status: :created, location: @inventory }
      else
        format.html { render action: 'new' }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:item_name, :sell_price, :high, :low)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_name %><br>
    <%= f.text_field :item_name %>
  </div>
  <div class="field">
    <%= f.label :sell_price %><br>
    <%= f.text_field :sell_price %>
  </div>
  <div class="field">
    <%= f.label :high %><br>
    <%= f.number_field :high %>
  </div>
  <div class="field">
    <%= f.label :low %><br>
    <%= f.number_field :low %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<h1>Listing inventories</h1>

<table>
  <thead>
    <tr>
      <th>Item name</th>
      <th>Sell price</th>
      <th>High</th>
      <th>Low</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.item_name %></td>
        <td><%= inventory.sell_price %></td>
        <td><%= inventory.high %></td>
        <td><%= inventory.low %></td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Delete', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Input New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item name:</strong>
  <%= @inventory.item_name %>
</p>

<p>
  <strong>Sell price:</strong>
  <%= @inventory.sell_price %>
</p>

<p>
  <strong>High:</strong>
  <%= @inventory.high %>
</p>

<p>
  <strong>Low:</strong>
  <%= @inventory.low %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>