config/routes.rb
Proj::Application.routes.draw do

  resources :selllines

  resources :invoices

  resources :orderlines

  resources :orders

  resources :inventories

  get 'invoices\ireport'=> 'invoices#ireport', as: "orderReport"
  get 'invoices\oreport'=> 'orders#oreport', as: "orepo"

end

app/models/sellline.rb
class Sellline < ActiveRecord::Base
  belongs_to :invoice
  belongs_to :inventory

  validates_numericality_of :quantity_sold,:only_integer => true
  validates :quantity_sold, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 30 }
  validates :invoice_id, :presence => true
  validates :inventory_id, :presence =>true
end

app/controllers/selllines_controller.rb
class SelllinesController < ApplicationController
  before_action :set_sellline, only: [:show, :edit, :update, :destroy]

  # GET /selllines
  # GET /selllines.json
  def index
    @selllines = Sellline.all
  end

  # GET /selllines/1
  # GET /selllines/1.json
  def show
  end

  # GET /selllines/new
  def new
    @sellline = Sellline.new
  end

  # GET /selllines/1/edit
  def edit
  end

  # POST /selllines
  # POST /selllines.json
  def create
    @sellline = Sellline.new(sellline_params)

    respond_to do |format|
      if @sellline.save
        format.html { redirect_to @sellline, notice: 'Sellline was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sellline }
      else
        format.html { render action: 'new' }
        format.json { render json: @sellline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selllines/1
  # PATCH/PUT /selllines/1.json
  def update
    respond_to do |format|
      if @sellline.update(sellline_params)
        format.html { redirect_to @sellline, notice: 'Sellline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sellline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selllines/1
  # DELETE /selllines/1.json
  def destroy
    @sellline.destroy
    respond_to do |format|
      format.html { redirect_to selllines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sellline
      @sellline = Sellline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sellline_params
      params.require(:sellline).permit(:invoice_id, :inventory_id, :quantity_sold)
    end
end

app/helpers/selllines_helper.rb
module SelllinesHelper
end

app/views/selllines/_form.html.erb
<%= form_for(@sellline) do |f| %>
  <% if @sellline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sellline.errors.count, "error") %> prohibited this sellline from being saved:</h2>

      <ul>
      <% @sellline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :invoice_id %><br>
    <%= f.collection_select :invoice_id, Invoice.all, :id, :id, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :inventory_id %><br>
    <%= f.collection_select :inventory_id,Inventory.all, :id, :item_name, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :quantity_sold %><br>
    <%= f.number_field :quantity_sold %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/selllines/edit.html.erb
<h1>Editing sellline</h1>

<%= render 'form' %>

<%= link_to 'Show', @sellline %> |
<%= link_to 'Back', selllines_path %>

app/views/selllines/index.html.erb
<h1>Listing selllines</h1>

<table>
  <thead>
    <tr>
      <th>Invoice</th>
      <th>Inventory</th>
      <th>Quantity sold</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @selllines.each do |sellline| %>
      <tr>
        <td><%= sellline.invoice_id %></td>
        <td><%= sellline.inventory_id %></td>
        <td><%= sellline.quantity_sold %></td>
        <td><%= link_to 'Show', sellline %></td>
        <td><%= link_to 'Edit', edit_sellline_path(sellline) %></td>
        <td><%= link_to 'Delete', sellline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sell line', new_sellline_path %>

app/views/selllines/new.html.erb
<h1>New sellline</h1>

<%= render 'form' %>

<%= link_to 'Back', selllines_path %>

app/views/selllines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice:</strong>
  <%= @sellline.invoice_id %>
</p>

<p>
  <strong>Inventory:</strong>
  <%= @sellline.inventory_id %>
</p>

<p>
  <strong>Quantity sold:</strong>
  <%= @sellline.quantity_sold %>
</p>

<%= link_to 'Edit', edit_sellline_path(@sellline) %> |
<%= link_to 'Back', selllines_path %>