config/routes.rb
Proj::Application.routes.draw do

  resources :selllines

  resources :invoices

  resources :orderlines

  resources :orders

  resources :inventories

  get 'invoices\ireport'=> 'invoices#ireport', as: "orderReport"
  get 'invoices\oreport'=> 'orders#oreport', as: "orepo"

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_many :selllines
  has_many :inventories, :through => :selllines
  validates :customer_name, :presence => true
  validates :customer_name, length: { maximum: 30}
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invoice }
      else
        format.html { render action: 'new' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:invoice_date, :customer_name)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :invoice_date %><br>
    <%= f.date_select :invoice_date %>
  </div>
  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Listing invoices</h1>

<table>
  <thead>
    <tr>
      <th>Invoice date</th>
      <th>Customer name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.invoice_date %></td>
        <td><%= invoice.customer_name %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/ireport.html.erb
<h1>Items Sold</h1>


<form action="">




  <p>Start Date
    <%= date_field_tag @invoice%></p>

  <p>End Date
    <%= date_field_tag @invoice %></p>


  <button>Submit</button>


</form>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Invoice date:</strong>
  <%= @invoice.invoice_date %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @invoice.customer_name %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>