config/routes.rb
Proj::Application.routes.draw do

  resources :selllines

  resources :invoices

  resources :orderlines

  resources :orders

  resources :inventories

  get 'invoices\ireport'=> 'invoices#ireport', as: "orderReport"
  get 'invoices\oreport'=> 'orders#oreport', as: "orepo"

end

app/models/orderline.rb
class Orderline < ActiveRecord::Base
  belongs_to :order
  belongs_to :inventory
  validates :order_id, :presence => true
  validates :inventory_id, :presence => true
  validates :quantity_ordered, :presence => true
  validates :quantity_received, :presence => true
  validates :cost_price, :presence => true
  validates_numericality_of :cost_price,:only_float => true
  validates_numericality_of :quantity_received,:only_integer => true
  validates_numericality_of :quantity_ordered,:only_integer => true
  validates :cost_price, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 1500 }
  validates :quantity_received, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 30 }
  validates_numericality_of :quantity_ordered, { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 30 }

end

app/controllers/orderlines_controller.rb
class OrderlinesController < ApplicationController
  before_action :set_orderline, only: [:show, :edit, :update, :destroy]

  # GET /orderlines
  # GET /orderlines.json
  def index
    @orderlines = Orderline.all
  end

  # GET /orderlines/1
  # GET /orderlines/1.json
  def show
  end

  # GET /orderlines/new
  def new
    @orderline = Orderline.new
  end

  # GET /orderlines/1/edit
  def edit
  end

  # POST /orderlines
  # POST /orderlines.json
  def create
    @orderline = Orderline.new(orderline_params)

    respond_to do |format|
      if @orderline.save
        format.html { redirect_to @orderline, notice: 'Orderline was successfully created.' }
        format.json { render action: 'show', status: :created, location: @orderline }
      else
        format.html { render action: 'new' }
        format.json { render json: @orderline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderlines/1
  # PATCH/PUT /orderlines/1.json
  def update
    respond_to do |format|
      if @orderline.update(orderline_params)
        format.html { redirect_to @orderline, notice: 'Orderline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @orderline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderlines/1
  # DELETE /orderlines/1.json
  def destroy
    @orderline.destroy
    respond_to do |format|
      format.html { redirect_to orderlines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderline
      @orderline = Orderline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orderline_params
      params.require(:orderline).permit(:order_id, :inventory_id, :quantity_received, :quantity_ordered, :cost_price)
    end
end

app/helpers/orderlines_helper.rb
module OrderlinesHelper
end

app/views/orderlines/_form.html.erb
<%= form_for(@orderline) do |f| %>
  <% if @orderline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orderline.errors.count, "error") %> prohibited this orderline from being saved:</h2>

      <ul>
      <% @orderline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.collection_select :order_id, Order.all, :id, :id, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :inventory_id %><br>
    <%= f.collection_select :inventory_id,Inventory.all, :id, :item_name, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :quantity_received %><br>
    <%= f.number_field :quantity_received %>
  </div>
  <div class="field">
    <%= f.label :quantity_ordered %><br>
    <%= f.number_field :quantity_ordered %>
  </div>
  <div class="field">
    <%= f.label :cost_price %><br>
    <%= f.text_field :cost_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orderlines/edit.html.erb
<h1>Editing orderline</h1>

<%= render 'form' %>

<%= link_to 'Show', @orderline %> |
<%= link_to 'Back', orderlines_path %>

app/views/orderlines/index.html.erb
<h1>Listing orderlines</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Inventory</th>
      <th>Quantity received</th>
      <th>Quantity ordered</th>
      <th>Cost price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orderlines.each do |orderline| %>
      <tr>
        <td><%= orderline.order_id %></td>
        <td><%= orderline.inventory_id %></td>
        <td><%= orderline.quantity_received %></td>
        <td><%= orderline.quantity_ordered %></td>
        <td><%= orderline.cost_price %></td>
        <td><%= link_to 'Show', orderline %></td>
        <td><%= link_to 'Edit', edit_orderline_path(orderline) %></td>
        <td><%= link_to 'Delete', orderline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orderline', new_orderline_path %>

app/views/orderlines/new.html.erb
<h1>New orderline</h1>

<%= render 'form' %>

<%= link_to 'Back', orderlines_path %>

app/views/orderlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @orderline.order_id %>
</p>

<p>
  <strong>Inventory:</strong>
  <%= @orderline.inventory_id %>
</p>

<p>
  <strong>Quantity received:</strong>
  <%= @orderline.quantity_received %>
</p>

<p>
  <strong>Quantity ordered:</strong>
  <%= @orderline.quantity_ordered %>
</p>

<p>
  <strong>Cost price:</strong>
  <%= @orderline.cost_price %>
</p>

<%= link_to 'Edit', edit_orderline_path(@orderline) %> |
<%= link_to 'Back', orderlines_path %>